<?php

return [
    'title' => 'Upute za administraciju',
    'intro' => 'Priručnik prati isti redoslijed kao lijeva navigacija. Odaberite područje, otvorite temu i slijedite preporučeni postupak.',
    'quick_start' => [
        [
            'title' => '1. Pronađite zapis',
            'text' => 'Koristite pretragu i filtre prije otvaranja zapisa. Tako smanjujete mogućnost uređivanja pogrešnog artikla, kategorije ili narudžbe.',
        ],
        [
            'title' => '2. Provjerite kontekst',
            'text' => 'Prije promjene provjerite jezik, status, izvor podatka i vrijedi li zapis za katalog, blog ili stranicu.',
        ],
        [
            'title' => '3. Spremite promjene',
            'text' => 'Najprije spremite osnovne podatke, a zatim uređujte slike, odnose, uvoz ili napredne postavke.',
        ],
        [
            'title' => '4. Provjerite rezultat',
            'text' => 'Nakon spremanja otvorite povezani ekran ili webshop i provjerite prikaz. Kod sinkronizacija pratite status u Izvršavanjima.',
        ],
    ],

    'sections' => [
        [
            'id' => 'nadzorna-ploca',
            'title' => 'Nadzorna ploča',
            'description' => 'Brzi pregled prodaje, narudžbi i aktivnosti trgovine.',
            'items' => [
                [
                    'id' => 'nadzorna-ploca-pregled',
                    'title' => 'Nadzorna ploča',
                    'route' => 'admin.dashboard',
                    'route_patterns' => ['admin.dashboard'],
                    'ability' => 'dashboard.view',
                    'purpose' => 'Prikazuje najvažnije pokazatelje trgovine, tijek narudžbi i nedavne aktivnosti na jednom mjestu.',
                    'steps' => [
                        'Odaberite razdoblje koje želite analizirati.',
                        'Pregledajte broj i vrijednost narudžbi te raspodjelu po statusima.',
                        'Kliknite karticu ili status kako biste otvorili filtriranu listu narudžbi.',
                        'Provjerite nedavne aktivnosti prije nastavka rada.',
                    ],
                    'fields' => [
                        ['name' => 'Razdoblje', 'description' => 'Mijenja vremenski raspon prikazanih pokazatelja.'],
                        ['name' => 'Tijek narudžbi', 'description' => 'Prikazuje koliko je narudžbi u pojedinom statusu obrade.'],
                        ['name' => 'Nedavna aktivnost', 'description' => 'Sažetak posljednjih važnih promjena u administraciji.'],
                    ],
                    'tips' => [
                        'Nadzorna ploča služi za pregled; obrada se nastavlja u odgovarajućem modulu.',
                        'Ako je modul isključen u Opcijama kataloga, njegove kartice mogu biti skrivene.',
                    ],
                ],
            ],
        ],

        [
            'id' => 'katalog',
            'title' => 'Katalog',
            'description' => 'Artikli, kategorije, svojstva, brendovi, akcije i B2B cijene.',
            'items' => [
                [
                    'id' => 'kategorije',
                    'title' => 'Kategorije',
                    'route' => 'admin.categories',
                    'route_patterns' => ['admin.categories*'],
                    'ability' => 'catalog.categories.view',
                    'purpose' => 'Organiziranje artikala, blogova i stranica u odvojena stabla te upravljanje nazivima, URL-ovima i prikazom u izborniku.',
                    'steps' => [
                        'Odaberite vrstu stabla i jezik koji uređujete.',
                        'Izaberite nadređenu kategoriju ili ostavite kategoriju na glavnoj razini.',
                        'Unesite naziv, stabilnu šifru i slug.',
                        'Podesite aktivnost, redoslijed, raspored i prikaz u izborniku.',
                        'Spremite zapis pa dodajte SEO podatke i slike.',
                    ],
                    'fields' => [
                        ['name' => 'Vrsta i roditelj', 'description' => 'Određuju stablo i položaj kategorije; roditelj mora biti u istoj vrsti stabla.'],
                        ['name' => 'Šifra', 'description' => 'Interni identifikator za povezivanja i uvoze; nakon povezivanja je ne mijenjajte.'],
                        ['name' => 'Naziv i slug', 'description' => 'Naziv koji korisnik vidi i dio javne web-adrese za odabrani jezik.'],
                        ['name' => 'Status i raspored', 'description' => 'Određuju je li kategorija vidljiva odmah ili samo u zadanom razdoblju.'],
                        ['name' => 'SEO i slike', 'description' => 'Meta naslov/opis te ikona ili banner kategorije.'],
                    ],
                    'warning' => 'Promjena sluga mijenja javni URL, a promjena roditelja mijenja cijelu strukturu navigacije. Prije spremanja provjerite povezane podkategorije.',
                ],
                [
                    'id' => 'artikli',
                    'title' => 'Artikli',
                    'route' => 'admin.products',
                    'route_patterns' => ['admin.products*'],
                    'ability' => 'catalog.products.view',
                    'purpose' => 'Centralno uređivanje proizvoda, cijene, zalihe, sadržaja, slika, kategorija, logistike i B2B podataka.',
                    'steps' => [
                        'Pronađite artikl filtrima ili izradite novi zapis.',
                        'Unesite i spremite osnovne podatke, cijenu, zalihu i prijevod.',
                        'Dodijelite kategorije, atribute i, ako se koriste, opcije artikla.',
                        'Uredite slike, logistiku, pakiranja, energetske podatke i B2B cijene.',
                        'Aktivirajte artikl i provjerite njegov prikaz na webshopu.',
                    ],
                    'fields' => [
                        ['name' => 'SKU i šifra', 'description' => 'Jedinstveni identifikatori artikla. Moraju ostati stabilni zbog ERP-a i dobavljačkih integracija.'],
                        ['name' => 'Cijena, zaliha i porez', 'description' => 'Osnovni prodajni podaci koji određuju dostupnost i izračun cijene.'],
                        ['name' => 'Naziv, slug i opis', 'description' => 'Sadržaj za odabrani jezik; slug određuje javni URL.'],
                        ['name' => 'Kategorije i brend', 'description' => 'Prva odabrana kategorija je primarna, a brend povezuje artikl sa stranicom proizvođača.'],
                        ['name' => 'Logistika', 'description' => 'Barkod, jedinica mjere, težina, dimenzije, količinski korak, pakiranja i oznake dostave.'],
                        ['name' => 'Energetski podaci', 'description' => 'Energetska klasa, EPREL broj, službena oznaka i informacijski list proizvoda.'],
                    ],
                    'warning' => 'Podaci označeni kao uvezeni iz M SAN-a mogu se promijeniti pri sljedećoj sinkronizaciji. Ručne promjene cijene ili zalihe radite tek nakon provjere pravila uvoza.',
                    'tips' => [
                        'Prazna cijena kombinacije opcija koristi osnovnu cijenu artikla.',
                        'Slike i povezane stavke uređujte nakon prvog spremanja novog artikla.',
                    ],
                ],
                [
                    'id' => 'atributi',
                    'title' => 'Atributi',
                    'route' => 'admin.attributes',
                    'route_patterns' => ['admin.attributes*'],
                    'ability' => 'catalog.attributes.view',
                    'feature' => 'attributes',
                    'purpose' => 'Definiranje opisnih svojstava i filtera, primjerice snage, boje, materijala ili kapaciteta.',
                    'steps' => [
                        'Izradite grupu atributa i odaberite dopušta li jednu ili više vrijednosti.',
                        'Dodajte vrijednosti u grupu i postavite njihov redoslijed.',
                        'Provjerite izvor podatka i status svake vrijednosti.',
                        'Dodijelite odgovarajuće vrijednosti artiklima.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra grupe i vrijednosti', 'description' => 'Stabilni ključevi koje mogu koristiti uvozi i filtri.'],
                        ['name' => 'Tip single/multi', 'description' => 'Određuje smije li artikl imati jednu ili više vrijednosti iz iste grupe.'],
                        ['name' => 'Naziv, slug i redoslijed', 'description' => 'Kontroliraju prikaz vrijednosti u administraciji i na webshopu.'],
                        ['name' => 'Izvor', 'description' => 'Pokazuje je li vrijednost unesena ručno ili njome upravlja dobavljačka integracija.'],
                    ],
                    'warning' => 'Atribut opisuje ili filtrira artikl, ali ne stvara zaseban SKU. Uvezene M SAN vrijednosti mogu se ponovno generirati.',
                ],
                [
                    'id' => 'opcije',
                    'title' => 'Opcije',
                    'route' => 'admin.options',
                    'route_patterns' => ['admin.options*'],
                    'ability' => 'catalog.options.view',
                    'feature' => 'options',
                    'purpose' => 'Upravljanje odabirima kupca koji mogu stvarati zasebne kombinacije SKU-a, cijene i zalihe.',
                    'steps' => [
                        'Izradite grupu opcija i odaberite način prikaza.',
                        'Dodajte vrijednosti te po potrebi uzorak boje ili sliku.',
                        'Dodijelite grupu opcija artiklu.',
                        'Na artiklu otvorite Vrijednosti opcija i izradite potrebne kombinacije.',
                        'Za svaku prodajnu kombinaciju unesite SKU, zalihu i eventualnu cijenu.',
                    ],
                    'fields' => [
                        ['name' => 'Tip prikaza', 'description' => 'Select, radio ili checkbox prikaz za kupca.'],
                        ['name' => 'Vrijednosti', 'description' => 'Mogu imati naziv, redoslijed, sliku ili uzorak boje.'],
                        ['name' => 'Kombinacijski SKU', 'description' => 'Jedinstvena šifra konkretne kombinacije opcija.'],
                        ['name' => 'Cijena i zaliha', 'description' => 'Posebne vrijednosti kombinacije; prazna cijena nasljeđuje osnovnu cijenu artikla.'],
                    ],
                    'warning' => 'Opcija označena samo kao filter ne stvara kupovnu kombinaciju. Opcije nemojte miješati s opisnim atributima.',
                ],
                [
                    'id' => 'brendovi',
                    'title' => 'Brendovi',
                    'route' => 'admin.manufacturers',
                    'route_patterns' => ['admin.manufacturers*'],
                    'ability' => 'catalog.manufacturers.view',
                    'feature' => 'manufacturers',
                    'purpose' => 'Uređivanje proizvođača i njihovih javnih stranica, logotipa, bannera i SEO podataka.',
                    'steps' => [
                        'Izradite brend i unesite stabilnu šifru.',
                        'Unesite naziv, slug i opis za odabrani jezik.',
                        'Dodajte SEO podatke, logo i banner.',
                        'Postavite redoslijed te status Aktivno ili Istaknuto.',
                        'Provjerite stranicu brenda i povezane artikle.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra', 'description' => 'Stabilni interni identifikator proizvođača.'],
                        ['name' => 'Slug', 'description' => 'Dio javne web-adrese stranice brenda.'],
                        ['name' => 'Aktivno / Istaknuto', 'description' => 'Kontrolira javnu dostupnost i isticanje brenda.'],
                        ['name' => 'Logo i banner', 'description' => 'Glavne vizualne datoteke za prikaz brenda.'],
                    ],
                    'warning' => 'Ako je brend povezan s artiklima, radije ga deaktivirajte nego brišite. Promjena sluga mijenja javni URL.',
                ],
                [
                    'id' => 'akcije-popusti',
                    'title' => 'Akcije i popusti',
                    'route' => 'admin.actions',
                    'route_patterns' => ['admin.actions*'],
                    'ability' => 'catalog.actions.view',
                    'feature' => 'actions',
                    'purpose' => 'Kreiranje vremenski ograničenih promotivnih pravila za artikle ili cijelu košaricu.',
                    'steps' => [
                        'Odaberite područje primjene i vrstu popusta.',
                        'Odredite ciljane artikle, kategorije, brendove ili košaricu.',
                        'Odredite publiku: svi, grupa ili pojedini korisnik.',
                        'Unesite vrijednost, kupon, prioritet, limite i razdoblje.',
                        'Aktivirajte pravilo i testirajte ga s konkretnim artiklom i korisnikom.',
                    ],
                    'fields' => [
                        ['name' => 'Vrsta i vrijednost', 'description' => 'Postotni ili fiksni popust te ostali podržani tipovi akcija.'],
                        ['name' => 'Cilj i publika', 'description' => 'Određuju na što se pravilo primjenjuje i tko ga može koristiti.'],
                        ['name' => 'Kupon i limiti', 'description' => 'Po potrebi zahtijevaju kod te ograničavaju ukupnu ili korisničku upotrebu.'],
                        ['name' => 'Prioritet i isključivost', 'description' => 'Određuju redoslijed obrade i smije li se akcija kombinirati s drugima.'],
                    ],
                    'warning' => 'Preklapanje više aktivnih pravila istog prioriteta može dati neočekivan izračun. Prije objave uvijek napravite testnu košaricu.',
                ],
                [
                    'id' => 'b2b-cjenici',
                    'title' => 'B2B cjenici',
                    'route' => 'admin.b2b-prices',
                    'route_patterns' => ['admin.b2b-prices*'],
                    'ability' => 'catalog.b2b_prices.view',
                    'purpose' => 'Ugovaranje posebnih cijena za B2B grupu ili pojedinačnog odobrenog kupca.',
                    'steps' => [
                        'Odaberite primjenjuje li se cjenik na grupu ili pojedinog B2B kupca.',
                        'Odaberite način izračuna cijene i unesite vrijednost.',
                        'Ograničite pravilo na katalog, kategoriju, brend ili odabrane artikle.',
                        'Postavite minimalnu količinu, valjanost i prioritet.',
                        'Aktivirajte pravilo i provjerite ga prijavom ciljnog kupca.',
                    ],
                    'fields' => [
                        ['name' => 'Publika', 'description' => 'Korisnička grupa ili pojedini odobreni B2B račun.'],
                        ['name' => 'Izračun', 'description' => 'Postotni popust, fiksni popust ili fiksna cijena.'],
                        ['name' => 'Cilj', 'description' => 'Cijeli katalog ili samo odabrane kategorije, brendovi i artikli.'],
                        ['name' => 'Valjanost i prioritet', 'description' => 'Vrijeme primjene i redoslijed kada se podudara više pravila.'],
                    ],
                    'warning' => 'Fiksna cijena primjenjuje se samo na izravno odabrane artikle. Ne miješajte ova pravila s cijenama po pakiranju unutar samog artikla.',
                ],
            ],
        ],

        [
            'id' => 'prodaja',
            'title' => 'Prodaja',
            'description' => 'Obrada narudžbi, dokumenata, dostave i zahtjeva za raskid.',
            'items' => [
                [
                    'id' => 'narudzbe',
                    'title' => 'Narudžbe',
                    'route' => 'admin.orders',
                    'route_patterns' => ['admin.orders*'],
                    'ability' => 'sales.orders.view',
                    'purpose' => 'Obrada narudžbi koje ostaju u CMS-u: provjera raspoloživosti i isporuke, komunikacija s kupcem, statusi, dokumenti i otprema.',
                    'steps' => [
                        'Pronađite narudžbu prema broju, kupcu, datumu ili statusu.',
                        'Provjerite kupca, adrese, stavke, raspoloživost, način plaćanja i dostavu.',
                        'Dodajte internu bilješku ili oznaku ako je potrebna dodatna obrada.',
                        'Promijenite status i zapišite razlog ili važnu napomenu.',
                        'Nakon provjere pošaljite ponudu ili račun te po potrebi izradite dostavnu naljepnicu.',
                    ],
                    'fields' => [
                        ['name' => 'Status', 'description' => 'Pokazuje gdje se narudžba nalazi u procesu obrade.'],
                        ['name' => 'Kupac i adrese', 'description' => 'Snimka podataka u trenutku naručivanja.'],
                        ['name' => 'Stavke i ukupni iznosi', 'description' => 'Naručeni artikli, količine, cijene, porez, popusti i dostava.'],
                        ['name' => 'Interna bilješka i oznake', 'description' => 'Podaci za podršku; ne prikazuju se kupcu osim ako je posebno navedeno.'],
                        ['name' => 'Povijest i transakcije', 'description' => 'Trag statusa, plaćanja, povrata i drugih promjena.'],
                    ],
                    'warning' => 'Produkcijske narudžbe ne brišite. Status plaćanja ili otkazivanja može utjecati na loyalty bodove, a promjena korisničkog profila ne mijenja spremljenu adresu narudžbe.',
                ],
                [
                    'id' => 'raskidi-ugovora',
                    'title' => 'Raskidi ugovora',
                    'route' => 'admin.withdrawals.index',
                    'route_patterns' => ['admin.withdrawals.*'],
                    'ability' => 'sales.withdrawals.view',
                    'purpose' => 'Obrada potrošačkih zahtjeva za raskid cijelog ugovora ili dijela narudžbe.',
                    'steps' => [
                        'Otvorite zahtjev i povezanu narudžbu.',
                        'Provjerite kupca, odabrane artikle i njegovu napomenu.',
                        'Obradite povrat prema pravilima trgovine.',
                        'Postavite status i dodajte internu bilješku.',
                        'Po potrebi ponovno pošaljite potvrdu kupcu.',
                    ],
                    'fields' => [
                        ['name' => 'Opseg zahtjeva', 'description' => 'Cijeli ugovor ili samo označene stavke narudžbe.'],
                        ['name' => 'Status obrade', 'description' => 'Evidentira zaprimanje, obradu, dovršetak ili odbijanje.'],
                        ['name' => 'Interna bilješka', 'description' => 'Bilješka za administratore i podršku, nije namijenjena kupcu.'],
                        ['name' => 'Obavijesti', 'description' => 'Status slanja potvrde kupcu i obavijesti trgovini.'],
                    ],
                    'warning' => 'Prije obrade provjerite adresu povrata, upute i adresu za obavijesti u Postavkama raskida.',
                ],
            ],
        ],

        [
            'id' => 'sadrzaj',
            'title' => 'Sadržaj',
            'description' => 'Upravljanje tekstovima, stranicama, blokovima i navigacijom webshopa.',
            'items' => [
                [
                    'id' => 'blog',
                    'title' => 'Blog',
                    'route' => 'admin.content.blog.index',
                    'route_patterns' => ['admin.content.blog.*'],
                    'ability' => 'content.blog.view',
                    'feature' => 'blog',
                    'purpose' => 'Objava novosti i članaka s naslovnom slikom, kategorijama, povezanim artiklima i SEO podacima.',
                    'steps' => [
                        'Izradite objavu i odaberite jezik.',
                        'Unesite naslov, slug, sažetak i puni sadržaj.',
                        'Dodijelite kategorije i, po potrebi, povezane artikle.',
                        'Dodajte naslovnu sliku, galeriju i SEO podatke.',
                        'Postavite datum objave, aktivnost i isticanje te provjerite javni prikaz.',
                    ],
                    'fields' => [
                        ['name' => 'Naslov i slug', 'description' => 'Naziv objave i njezina javna web-adresa za odabrani jezik.'],
                        ['name' => 'Sažetak i sadržaj', 'description' => 'Kratki prikaz na listi i puni sadržaj članka.'],
                        ['name' => 'Objava i istaknuto', 'description' => 'Kontroliraju vidljivost, termin objave i prioritet prikaza.'],
                        ['name' => 'Kategorije i artikli', 'description' => 'Povezuju objavu s temama i proizvodima.'],
                    ],
                    'warning' => 'Promjena sluga mijenja javni URL. Zakazanu objavu provjerite u vremenskoj zoni koju koristi trgovina.',
                ],
                [
                    'id' => 'stranice',
                    'title' => 'Stranice',
                    'route' => 'admin.content.pages.index',
                    'route_patterns' => ['admin.content.pages.*'],
                    'ability' => 'content.pages.view',
                    'purpose' => 'Uređivanje trajnih informativnih stranica poput dostave, plaćanja, privatnosti i uvjeta kupnje.',
                    'steps' => [
                        'Izradite stranicu i odaberite jezik.',
                        'Unesite naslov, slug i sadržaj.',
                        'Odaberite izgled stranice i eventualnu kategoriju.',
                        'Postavite prikaz u footeru, redoslijed i aktivnost.',
                        'Dodajte SEO podatke i provjerite javni URL.',
                    ],
                    'fields' => [
                        ['name' => 'Naslov i slug', 'description' => 'Vidljivi naslov i javna adresa stranice.'],
                        ['name' => 'Sadržaj', 'description' => 'Glavni tekst stranice s podrškom za oblikovanje.'],
                        ['name' => 'Layout i kategorija', 'description' => 'Određuju predložak i grupiranje stranice.'],
                        ['name' => 'Footer i redoslijed', 'description' => 'Određuju prikazuje li se stranica među poveznicama u podnožju.'],
                    ],
                    'warning' => 'Pravne stranice nemojte brisati bez prethodne provjere linkova iz footera, checkouta i privola.',
                ],
                [
                    'id' => 'faq',
                    'title' => 'FAQ',
                    'route' => 'admin.content.faqs.index',
                    'route_patterns' => ['admin.content.faqs.*'],
                    'ability' => 'content.faqs.view',
                    'purpose' => 'Upravljanje često postavljanim pitanjima grupiranima po temi i jeziku.',
                    'steps' => [
                        'Izradite pitanje i odaberite jezik.',
                        'Unesite pitanje, slug i oblikovani odgovor.',
                        'Dodijelite grupu i redoslijed.',
                        'Postavite aktivnost i po potrebi označite pitanje kao istaknuto.',
                        'Provjerite prikaz na FAQ stranici.',
                    ],
                    'fields' => [
                        ['name' => 'Pitanje i slug', 'description' => 'Tekst pitanja i njegov stabilni URL identifikator.'],
                        ['name' => 'Odgovor', 'description' => 'Puni odgovor koji se prikazuje posjetitelju.'],
                        ['name' => 'Grupa i redoslijed', 'description' => 'Organiziraju pitanja u pregledne cjeline.'],
                        ['name' => 'Istaknuto', 'description' => 'Daje pitanju veću vidljivost kada je podržano predloškom.'],
                    ],
                    'tips' => ['Jedno pitanje neka rješava jednu temu; dugačke odgovore podijelite na kraće odlomke.'],
                ],
                [
                    'id' => 'komentari',
                    'title' => 'Komentari',
                    'route' => 'admin.content.comments.index',
                    'route_patterns' => ['admin.content.comments.*'],
                    'ability' => 'content.comments.view',
                    'purpose' => 'Moderiranje komentara korisnika na artiklima i drugim podržanim sadržajima.',
                    'steps' => [
                        'Filtrirajte komentare prema statusu ili pronađite autora i sadržaj.',
                        'Otvorite komentar i provjerite kontekst u kojem je objavljen.',
                        'Odobrite ispravan komentar ili ga označite kao odbijen/spam.',
                        'Koristite brisanje samo kada zapis više ne treba ostati u moderacijskom tijeku.',
                    ],
                    'fields' => [
                        ['name' => 'Status', 'description' => 'Na čekanju, odobreno, odbijeno ili spam.'],
                        ['name' => 'Autor i sadržaj', 'description' => 'Identitet pošiljatelja i tekst koji se moderira.'],
                        ['name' => 'Povezani zapis', 'description' => 'Artikl ili sadržaj na kojem je komentar ostavljen.'],
                    ],
                    'warning' => 'Prije označavanja kao spam provjerite kontekst. Vraćanje obrisanog zapisa koristite samo kada je komentar greškom uklonjen.',
                ],
                [
                    'id' => 'blokovi',
                    'title' => 'Blokovi',
                    'route' => 'admin.content.blocks',
                    'route_patterns' => ['admin.content.blocks*', 'admin.content.slots*'],
                    'ability' => 'content.blocks.view',
                    'purpose' => 'Sastavljanje ponovljivih dijelova naslovnice i drugih stranica, primjerice bannera, izdvojenih artikala, brendova ili vijesti.',
                    'steps' => [
                        'Odaberite vrstu bloka i unesite jasan naziv te stabilnu šifru.',
                        'Odaberite poziciju, površinu, uređaj i eventualni ciljani zapis.',
                        'Unesite lokalizirani naslov, podnaslov, CTA i stil.',
                        'Za blokove s podacima odaberite artikle, kategorije, brendove ili objave i složite njihov redoslijed.',
                        'Postavite raspored, spremite i provjerite preview na odgovarajućoj stranici.',
                    ],
                    'fields' => [
                        ['name' => 'Vrsta i šifra', 'description' => 'Određuju ponašanje bloka i stabilni identitet za pozicioniranje.'],
                        ['name' => 'Pozicija i cilj', 'description' => 'Određuju gdje se blok prikazuje i vrijedi li globalno ili samo na određenoj stranici.'],
                        ['name' => 'Uređaj i status', 'description' => 'Kontroliraju desktop/mobilni prikaz, aktivnost i razdoblje.'],
                        ['name' => 'Odabrane stavke', 'description' => 'Sadržaj i redoslijed proizvoda, brendova, kategorija ili objava.'],
                    ],
                    'warning' => 'Za globalni blok cilj ostavite prazan. Promjenu pozicije uvijek provjerite na desktopu i mobitelu prije objave.',
                ],
                [
                    'id' => 'navigacija',
                    'title' => 'Navigacija',
                    'route' => 'admin.content.navigation',
                    'route_patterns' => ['admin.content.navigation*'],
                    'ability' => 'content.navigation.view',
                    'purpose' => 'Upravljanje glavnim desktop i mobilnim izbornikom, gornjom trakom i istaknutim poveznicama webshopa.',
                    'steps' => [
                        'Odaberite jezik navigacije.',
                        'Dodajte katalog, kategoriju, stranicu, blog, kontakt, FAQ ili vlastitu poveznicu.',
                        'Složite redoslijed i podesite aktivnost, padajući izbornik, isticanje i otvaranje u novom tabu.',
                        'Po potrebi uredite izgled, promo sadržaj mega-menija, gornju traku i društvene mreže.',
                        'Spremite i provjerite desktop i mobilni izbornik.',
                    ],
                    'fields' => [
                        ['name' => 'Vrsta stavke', 'description' => 'Određuje je li poveznica vezana uz sustavski sadržaj ili vlastiti URL.'],
                        ['name' => 'Naziv', 'description' => 'Prazno polje koristi automatski naziv povezanog sadržaja; unesena vrijednost ga nadjačava.'],
                        ['name' => 'Dropdown / Istaknuto', 'description' => 'Uključuje podkategorije i posebnu boju za važnu stavku.'],
                        ['name' => 'Gornja traka', 'description' => 'Dodatni linkovi, boje i ikone društvenih mreža iznad glavne navigacije.'],
                    ],
                    'warning' => 'Nakon promjene provjerite da sve interne i vanjske poveznice rade te da izbornik stane na manjim ekranima.',
                ],
            ],
        ],

        [
            'id' => 'integracije',
            'title' => 'Integracije',
            'description' => 'Povezivanje dobavljačkih podataka s lokalnim katalogom.',
            'items' => [
                [
                    'id' => 'msan-pregled',
                    'title' => 'M SAN — Pregled',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.overview',
                    'route_patterns' => ['admin.integrations.msan.overview'],
                    'ability' => 'integrations.msan.view',
                    'purpose' => 'Središnje mjesto za stanje M SAN veze, sažetak kataloga i ručno pokretanje sinkronizacija.',
                    'steps' => [
                        'Provjerite kartice s brojem artikala, odabranih stavki, kategorija i specifikacija.',
                        'Kliknite Provjeri vezu prije prvog ili problematičnog dohvata.',
                        'Pokrenite Dohvati katalog za osvježavanje privremenog dobavljačkog kataloga.',
                        'Po potrebi pokrenite osvježavanje cijena i količina, specifikacija ili EPREL-a.',
                        'Pratite zadnje izvršavanje i otvorite povijest ako postoji greška.',
                    ],
                    'fields' => [
                        ['name' => 'Spremnost veze', 'description' => 'Pokazuje jesu li uključene i spremljene potrebne postavke.'],
                        ['name' => 'KPI kartice', 'description' => 'Brzi broj artikala, odabira, uvoza, kategorija i specifikacija.'],
                        ['name' => 'Zadnje izvršavanje', 'description' => 'Status, napredak i poruka posljednjeg posla.'],
                    ],
                    'warning' => 'Puni dohvat samo puni lokalni privremeni katalog. Artikli ne ulaze automatski u webshop dok se ne mapiraju kategorije, odaberu stavke i pokrene uvoz.',
                ],
                [
                    'id' => 'msan-postavke',
                    'title' => 'M SAN — Postavke',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.settings',
                    'route_patterns' => ['admin.integrations.msan.settings'],
                    'ability' => 'integrations.msan.settings.manage',
                    'purpose' => 'Konfiguriranje B2B veze, certifikata, automatskog osvježavanja, slika, specifikacija, EPREL-a i pravila uvoza.',
                    'steps' => [
                        'Uključite M SAN i učitajte P12/PFX certifikat s pripadajućim PIN-om.',
                        'Spremite promjene pa provjerite B2B vezu.',
                        'Ako koristite slike, uključite FTP/FTPS, unesite pristupne podatke i provjerite vezu.',
                        'Podesite raspored cijena i zaliha, izvore specifikacija i EPREL pristup.',
                        'Odaberite pravila uvoza i maksimalne lokalne količine za svaku razinu raspoloživosti.',
                    ],
                    'fields' => [
                        ['name' => 'Certifikat i PIN', 'description' => 'Privatni pristup M SAN B2B servisu; prazna tajna zadržava već spremljenu vrijednost.'],
                        ['name' => 'Cron raspored', 'description' => 'Automatsko osvježavanje cijena i količina u vremenskoj zoni Europe/Zagreb.'],
                        ['name' => 'FTP/FTPS slike', 'description' => 'Pristup slikama koje se preuzimaju i spremaju lokalno.'],
                        ['name' => 'Specifikacije i EPREL', 'description' => 'Izvor, vremenska ograničenja, API ključ i opseg sinkronizacije.'],
                        ['name' => 'Pravila uvoza', 'description' => 'Određuju koje podatke dobavljač smije mijenjati i kako se razine zalihe pretvaraju u količine.'],
                    ],
                    'warning' => 'Najprije spremite postavke, a tek zatim koristite gumbe za provjeru veze. Certifikat, PIN i API ključeve ne šaljite e-poštom niti ih unosite u opisne bilješke.',
                ],
                [
                    'id' => 'msan-kategorije',
                    'title' => 'M SAN — Mapiranje kategorija',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.categories',
                    'route_patterns' => ['admin.integrations.msan.categories'],
                    'ability' => 'integrations.msan.view',
                    'purpose' => 'Povezivanje kategorija dobavljača s kategorijama webshopa kako bi artikli mogli biti uvezeni na pravo mjesto.',
                    'steps' => [
                        'Filtrirajte nemapirane kategorije, po potrebi samo one koje sadrže artikle.',
                        'Koristite Sigurno spoji jednake nazive samo za očita i jedinstvena podudaranja.',
                        'Za ostale kategorije ručno odaberite odgovarajuću kategoriju webshopa ili uvezite cijelu granu.',
                        'Po potrebi postavite EPREL grupu i pravilo energetske oznake.',
                        'Spremite mapiranje ili svjesno označite kategoriju za ignoriranje.',
                    ],
                    'fields' => [
                        ['name' => 'Status', 'description' => 'Nije mapirano, mapirano ili ignorirano.'],
                        ['name' => 'Kategorija webshopa', 'description' => 'Lokalna kategorija u koju će biti smješteni uvezeni artikli.'],
                        ['name' => 'Uvoz grane', 'description' => 'Po želji izrađuje cijelu dobavljačku granu ispod odabranog lokalnog roditelja.'],
                        ['name' => 'EPREL pravilo', 'description' => 'Pomaže odrediti očekivane energetske podatke za artikle kategorije.'],
                    ],
                    'warning' => 'Artikl nije spreman za uvoz dok njegova kategorija nije valjano mapirana. Ignoriranje znači da će se cijela kategorija preskakati.',
                ],
                [
                    'id' => 'msan-specifikacije',
                    'title' => 'M SAN — Specifikacije',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.specifications',
                    'route_patterns' => ['admin.integrations.msan.specifications*'],
                    'ability' => 'integrations.msan.view',
                    'purpose' => 'Određivanje koje se dobavljačke specifikacije uvoze, kako se nazivaju i koriste li se kao filteri.',
                    'steps' => [
                        'Pretražite specifikaciju ili filtrirajte prema uvozu, namjeni i aktualnosti.',
                        'Otvorite pravilo i po potrebi prilagodite naziv grupe, stavke i mjerne jedinice.',
                        'Odaberite namjenu podatka.',
                        'Uključite Uvezi podatak i, ako treba, Koristi kao filtar.',
                        'Spremite pravilo i provjerite rezultat nakon sljedećeg dohvata specifikacija.',
                    ],
                    'fields' => [
                        ['name' => 'Prikazni nazivi', 'description' => 'Nazivi koje kupac vidi; prazno polje zadržava izvorni M SAN naziv.'],
                        ['name' => 'Namjena podatka', 'description' => 'Razvrstava specifikaciju prema ulozi u katalogu i energetskim podacima.'],
                        ['name' => 'Uvezi podatak', 'description' => 'Isključena specifikacija neće se objaviti na artiklu.'],
                        ['name' => 'Koristi kao filtar', 'description' => 'Pretvara vrijednosti specifikacije u filtrirajuća svojstva artikla.'],
                    ],
                    'warning' => 'Promjena pravila utječe na buduće sinkronizacije. Nakon veće promjene provjerite nekoliko artikala prije masovnog osvježavanja.',
                ],
                [
                    'id' => 'msan-artikli',
                    'title' => 'M SAN — Odabir artikala',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.products',
                    'route_patterns' => ['admin.integrations.msan.products'],
                    'ability' => 'integrations.msan.view',
                    'purpose' => 'Sastavljanje zajedničke radne liste dobavljačkih artikala koji će se uvesti u webshop.',
                    'steps' => [
                        'Filtrirajte artikle po nazivu, kategoriji, proizvođaču, raspoloživosti ili statusu uvoza.',
                        'Uključite pojedine artikle ili masovno uključite sve spremne filtrirane rezultate.',
                        'Pregledajte broj odabranih i spremnih stavki u ljepljivom sažetku.',
                        'Kliknite Uvezi odabrane i pratite posao u Izvršavanjima.',
                        'Uvezene artikle zatim doradite u Katalogu pod Artikli.',
                    ],
                    'fields' => [
                        ['name' => 'Radna lista', 'description' => 'Zajednički, odmah spremljen odabir artikala za uvoz.'],
                        ['name' => 'Spremnost', 'description' => 'Ovisi o dostupnosti artikla i valjano mapiranoj kategoriji.'],
                        ['name' => 'Status uvoza', 'description' => 'Pokazuje je li artikl nov, spreman, uvezen ili blokiran.'],
                    ],
                    'warning' => 'Uvezi odabrane obrađuje cijelu zajedničku radnu listu, a ne samo trenutno filtrirane retke. Prije pokretanja provjerite ukupni broj.',
                ],
                [
                    'id' => 'msan-izvrsavanja',
                    'title' => 'M SAN — Izvršavanja',
                    'eyebrow' => 'M SAN',
                    'route' => 'admin.integrations.msan.runs',
                    'route_patterns' => ['admin.integrations.msan.runs'],
                    'ability' => 'integrations.msan.view',
                    'purpose' => 'Povijest svih M SAN sinkronizacija i uvoza sa statusom, trajanjem, brojevima obrađenih stavki i pogreškama.',
                    'steps' => [
                        'Filtrirajte izvršavanja prema vrsti ili statusu.',
                        'Za posao u tijeku pratite napredak i osvježite prikaz.',
                        'Kod neuspjeha prvo pročitajte poruku i detalj pogreške.',
                        'Provjerite koliko je stavki obrađeno, preskočeno ili neuspješno prije ponovnog pokretanja.',
                    ],
                    'fields' => [
                        ['name' => 'Vrsta i status', 'description' => 'Pokazuju koji je posao pokrenut i je li završio uspješno.'],
                        ['name' => 'Napredak i trajanje', 'description' => 'Daju uvid u tijek i trajanje pozadinske obrade.'],
                        ['name' => 'Brojevi i pogreška', 'description' => 'Sažetak uspješnih, preskočenih i problematičnih zapisa.'],
                    ],
                    'tips' => ['Ne pokrećite isti veliki posao ponovno dok je prethodni još u tijeku.'],
                ],
            ],
        ],

        [
            'id' => 'postavke',
            'title' => 'Postavke',
            'description' => 'Plaćanje, dostava, lokalni šifrarnici, sustav, API i korisnički moduli.',
            'items' => [
                [
                    'id' => 'nacini-placanja',
                    'title' => 'Načini plaćanja',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'payment-methods'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Uključivanje, redoslijed i konfiguracija načina plaćanja dostupnih kupcu u checkoutu.',
                    'steps' => [
                        'Otvorite postojeći način plaćanja ili izradite novi.',
                        'Odaberite vrstu i davatelja usluge te unesite naziv i opis za kupca.',
                        'Podesite aktivnost, redoslijed, podržane valute i eventualne limite.',
                        'Za kartično plaćanje unesite podatke odabranog gatewaya i spremite.',
                        'Napravite testnu narudžbu prije uključivanja metode kupcima.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra i provider', 'description' => 'Stabilno određuju integraciju: uplata/ponuda, WSPay, Corvus, KEKS ili druga podržana metoda.'],
                        ['name' => 'Aktivno i redoslijed', 'description' => 'Kontroliraju dostupnost i poziciju u checkoutu.'],
                        ['name' => 'Konfiguracija gatewaya', 'description' => 'Trgovački identifikatori, ključevi i testni/produkcijski način rada.'],
                    ],
                    'warning' => 'Novi kartični gateway nemojte uključiti dok nisu potvrđeni produkcijski podaci i uspješno testirani povratni statusi plaćanja.',
                ],
                [
                    'id' => 'nacini-dostave',
                    'title' => 'Načini dostave',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.shipping.index',
                    'route_patterns' => ['admin.shipping.*', 'admin.settings.local.shipping-redirect'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Definiranje dostupnih dostavnih službi, cijena, besplatne dostave i ograničenja po paketu ili odredištu.',
                    'steps' => [
                        'Izradite ili otvorite način dostave i odaberite prijevoznika.',
                        'Unesite osnovnu cijenu ili prag besplatne dostave.',
                        'Postavite geo zonu, limite težine/dimenzija i pravila za posebne oznake artikla.',
                        'Po potrebi dodajte težinske razrede ili konfigurirajte BOX NOW/GLS integraciju.',
                        'Spremite i testirajte nekoliko različitih košarica i adresa.',
                    ],
                    'fields' => [
                        ['name' => 'Cijena i besplatna dostava', 'description' => 'Osnovni trošak i iznos košarice iznad kojeg je dostava besplatna.'],
                        ['name' => 'Geo zona', 'description' => 'Područje na kojem je način dostave dostupan.'],
                        ['name' => 'Ograničenja', 'description' => 'Težina, dimenzije, krhko, vangabaritno, teško i druga pravila prihvatljivosti.'],
                        ['name' => 'Integracija prijevoznika', 'description' => 'Pristupni podaci i posebna pravila za BOX NOW ili GLS kada su ugovoreni.'],
                    ],
                    'warning' => 'BOX NOW nemojte aktivirati prije dogovorene suradnje i potvrđenih ormarića/API pristupa. Nakon promjene cijena obavezno testirajte otoke i rubne zone.',
                ],
                [
                    'id' => 'geo-zone',
                    'title' => 'Geo zone',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'geo-zones'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Grupiranje država i regija u područja na koja se primjenjuju dostava, porezi ili druga lokalna pravila.',
                    'steps' => [
                        'Izradite zonu s jasnim nazivom i stabilnom šifrom.',
                        'Dodajte države i, kada je potrebno, ograničite zonu na regije.',
                        'Povežite zonu s načinima dostave ili drugim pravilima.',
                        'Provjerite da se zone ne preklapaju na neželjen način.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra', 'description' => 'Stabilni interni ključ geo zone.'],
                        ['name' => 'Naziv i status', 'description' => 'Administrativni naziv i uključenost zone.'],
                    ],
                    'warning' => 'Promjena zone može odmah promijeniti dostupnost i cijenu dostave za veći broj kupaca.',
                ],
                [
                    'id' => 'drzave-geo-zona',
                    'title' => 'Države geo zona',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'geo-zone-countries'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Povezivanje država i njihovih regija s definiranim geo zonama.',
                    'steps' => [
                        'Odaberite geo zonu.',
                        'Odaberite državu i po potrebi konkretnu regiju.',
                        'Spremite zapis i provjerite da ista kombinacija nije nepotrebno duplicirana.',
                        'Testirajte adresu iz te države ili regije u checkoutu.',
                    ],
                    'fields' => [
                        ['name' => 'Geo zona', 'description' => 'Ciljna grupa pravila.'],
                        ['name' => 'Država i regija', 'description' => 'Područje koje se pridružuje zoni; prazna regija obično znači cijelu državu.'],
                    ],
                    'warning' => 'Općenito pravilo za državu može prekriti posebno pravilo za regiju. Provjerite redoslijed i očekivani rezultat.',
                ],
                [
                    'id' => 'regije',
                    'title' => 'Regije / županije',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'regions'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Šifrarnik regija i županija koji se koristi za adrese, geo zone i posebna pravila dostave.',
                    'steps' => [
                        'Pronađite postojeću regiju prije dodavanja nove.',
                        'Unesite državu, naziv i stabilnu šifru.',
                        'Postavite redoslijed i aktivnost.',
                        'Povežite regiju s geo zonom ako za nju vrijedi posebno pravilo.',
                    ],
                    'fields' => [
                        ['name' => 'Država', 'description' => 'Država kojoj regija pripada.'],
                        ['name' => 'Šifra i naziv', 'description' => 'Stabilni identifikator i naziv koji administrator prepoznaje.'],
                    ],
                    'warning' => 'Duplikati ili promjena šifre mogu poremetiti postojeće geo-zone i checkout adrese.',
                ],
                [
                    'id' => 'valute',
                    'title' => 'Valute',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'currencies'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Definiranje valuta, simbola, formata i osnovne valute trgovine.',
                    'steps' => [
                        'Provjerite postoji li valuta prije izrade nove.',
                        'Unesite ISO šifru, naziv, simbol i broj decimala.',
                        'Postavite tečaj prema osnovnoj valuti.',
                        'Označite osnovnu valutu samo ako namjerno mijenjate cijeli obračun trgovine.',
                    ],
                    'fields' => [
                        ['name' => 'ISO šifra', 'description' => 'Troslovna oznaka, primjerice EUR.'],
                        ['name' => 'Simbol i decimale', 'description' => 'Način prikaza iznosa kupcu.'],
                        ['name' => 'Tečaj i osnovna valuta', 'description' => 'Odnos prema glavnoj valuti sustava.'],
                    ],
                    'warning' => 'Promjena osnovne valute ili tečaja utječe na prikaz cijena i izvještaje. Radite je samo uz provjeru svih integracija.',
                ],
                [
                    'id' => 'porezne-stope',
                    'title' => 'Porezne stope',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'tax-rates'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Šifrarnik poreznih stopa koje se dodjeljuju artiklima i koriste u izračunu narudžbe.',
                    'steps' => [
                        'Izradite stopu s jasnom šifrom i nazivom.',
                        'Unesite postotak i postavite aktivnost.',
                        'Dodijelite stopu odgovarajućim artiklima.',
                        'Provjerite testni izračun cijene i poreza u košarici.',
                    ],
                    'fields' => [
                        ['name' => 'Stopa', 'description' => 'Postotak poreza koji se primjenjuje.'],
                        ['name' => 'Šifra i naziv', 'description' => 'Stabilni ključ i razumljiv naziv porezne klase.'],
                    ],
                    'warning' => 'Porezne stope mijenjajte samo prema uputi računovodstva. Promjena može utjecati na sve nove narudžbe povezanih artikala.',
                ],
                [
                    'id' => 'statusi-narudzbi',
                    'title' => 'Statusi narudžbi',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'order-statuses'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Definiranje koraka kroz koje narudžba prolazi od zaprimanja do dovršetka ili otkazivanja.',
                    'steps' => [
                        'Pregledajte postojeći tijek prije dodavanja novog statusa.',
                        'Unesite stabilnu šifru, naziv i boju.',
                        'Postavite redoslijed i zastavice ponašanja statusa.',
                        'Provjerite kako promjena utječe na plaćanje, obavijesti i loyalty.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra', 'description' => 'Stabilni ključ koji koriste automatizacije i integracije.'],
                        ['name' => 'Naziv, boja i redoslijed', 'description' => 'Prikaz statusa administratoru i kupcu.'],
                        ['name' => 'Sistemske zastavice', 'description' => 'Označavaju stanja poput plaćeno, dovršeno ili otkazano.'],
                    ],
                    'warning' => 'Ne mijenjajte šifre postojećih sistemskih statusa bez provjere koda, payment gatewaya i ERP povezivanja.',
                ],
                [
                    'id' => 'jezici',
                    'title' => 'Jezici',
                    'eyebrow' => 'Lokalno',
                    'route' => 'admin.settings.local.resource',
                    'route_parameters' => ['resource' => 'languages'],
                    'route_patterns' => ['admin.settings.local.resource*'],
                    'ability' => 'settings.local.manage',
                    'purpose' => 'Upravljanje jezicima i lokalizacijama sadržaja webshopa.',
                    'steps' => [
                        'Provjerite postoji li jezik i jesu li prijevodi sadržaja pripremljeni.',
                        'Unesite kod jezika, locale, naziv i izvorni naziv.',
                        'Postavite smjer teksta, redoslijed i aktivnost.',
                        'Odredite zadani jezik samo kada je sav ključni sadržaj spreman.',
                    ],
                    'fields' => [
                        ['name' => 'Kod i locale', 'description' => 'Tehničke oznake jezika, primjerice hr i hr_HR.'],
                        ['name' => 'Nazivi', 'description' => 'Administrativni i izvorni naziv jezika.'],
                        ['name' => 'Zadano / Aktivno', 'description' => 'Kontroliraju početni jezik i dostupnost posjetiteljima.'],
                    ],
                    'warning' => 'Ne uključujte novi jezik prije nego što su prevedeni navigacija, ključne stranice, kategorije i aktivni artikli.',
                ],
                [
                    'id' => 'runtime-kontrole',
                    'title' => 'Runtime kontrole',
                    'eyebrow' => 'Sustav',
                    'route' => 'admin.settings.system.runtime',
                    'route_patterns' => ['admin.settings.system.runtime', 'admin.system.*'],
                    'ability' => 'settings.system.runtime.manage',
                    'purpose' => 'Uključivanje maintenance načina i ručno čišćenje aplikacijskog cachea.',
                    'steps' => [
                        'Maintenance uključite samo za planirani kratki zahvat.',
                        'Provjerite da administratori i dalje mogu pristupiti sustavu.',
                        'Očistite cache nakon promjena konfiguracije ili ako se stari prikaz zadržava.',
                        'Po završetku obavezno isključite maintenance i otvorite frontend.',
                    ],
                    'warning' => 'Maintenance privremeno onemogućuje kupnju posjetiteljima. Ne ostavljajte ga uključenog nakon završetka radova.',
                ],
                [
                    'id' => 'izgled-admina',
                    'title' => 'Izgled admina',
                    'eyebrow' => 'Sustav',
                    'route' => 'admin.settings.system.admin-appearance-controls',
                    'route_patterns' => ['admin.settings.system.admin-appearance-controls'],
                    'ability' => 'settings.system.admin_appearance.manage',
                    'purpose' => 'Podešavanje broja zapisa po stranici i drugih zajedničkih postavki prikaza administracije.',
                    'steps' => [
                        'Odaberite razumne veličine lista za administraciju.',
                        'Posebno podesite broj korijenskih kategorija ako je stablo veliko.',
                        'Spremite i provjerite nekoliko najčešće korištenih lista.',
                    ],
                    'warning' => 'Prevelik broj stavki po stranici može usporiti učitavanje velikih kataloga i narudžbi.',
                ],
                [
                    'id' => 'opcije-kataloga',
                    'title' => 'Opcije kataloga',
                    'eyebrow' => 'Sustav',
                    'route' => 'admin.settings.system.catalog-features',
                    'route_patterns' => ['admin.settings.system.catalog-features'],
                    'ability' => 'settings.system.catalog_features.manage',
                    'purpose' => 'Uključivanje ili skrivanje opcijskih modula poput bloga, atributa, opcija, brendova, akcija i API-ja.',
                    'steps' => [
                        'Provjerite koristi li trgovina podatke modula koji želite promijeniti.',
                        'Uključite ili isključite samo jednu povezanu grupu funkcija odjednom.',
                        'Spremite i provjerite navigaciju administracije te relevantne stranice webshopa.',
                    ],
                    'warning' => 'Isključivanje skriva modul i njegove rute, ali ne briše podatke. Ipak, može sakriti sadržaj ili ponašanje na webshopu pa promjenu prvo uskladite s urednicima.',
                ],
                [
                    'id' => 'postavke-trgovine',
                    'title' => 'Postavke trgovine',
                    'eyebrow' => 'Sustav',
                    'route' => 'admin.settings.system.store-settings',
                    'route_patterns' => ['admin.settings.system.store-settings'],
                    'ability' => 'settings.system.store.manage',
                    'purpose' => 'Centralne postavke identiteta trgovine, e-pošte, integracija, cijena, slika, SEO-a, objava i kolačića.',
                    'steps' => [
                        'Odaberite karticu koju želite uređivati.',
                        'Promijenite samo podatke povezane s tom karticom.',
                        'Spremite aktivnu karticu prije prelaska na drugu.',
                        'Provjerite frontend, e-poštu ili integraciju na koju se promjena odnosi.',
                    ],
                    'fields' => [
                        ['name' => 'Email', 'description' => 'Adrese pošiljatelja i primatelja sistemskih poruka.'],
                        ['name' => 'Branding i Footer', 'description' => 'Naziv, logo, kontaktni i footer podaci trgovine.'],
                        ['name' => 'Integrations i Pricing', 'description' => 'Vanjske usluge te opća pravila cijena i prikaza.'],
                        ['name' => 'Images i Proizvodi', 'description' => 'Zadane slike i ponašanje prikaza artikala.'],
                        ['name' => 'SEO, OG/Twitter i Schema', 'description' => 'Podaci za tražilice i dijeljenje na društvenim mrežama.'],
                        ['name' => 'Announcement i Cookies', 'description' => 'Obavijesti kupcima i postavke privola/kolačića.'],
                    ],
                    'warning' => 'Sprema se samo trenutno otvorena kartica. Prije prelaska na drugu karticu spremite promjene.',
                ],
                [
                    'id' => 'postavke-raskida',
                    'title' => 'Postavke raskida',
                    'eyebrow' => 'Sustav',
                    'route' => 'admin.settings.system.withdrawal-settings',
                    'route_patterns' => ['admin.settings.system.withdrawal-settings'],
                    'ability' => 'settings.system.store.manage',
                    'purpose' => 'Podešavanje obavijesti, adrese povrata i uputa koje se koriste kod raskida ugovora.',
                    'steps' => [
                        'Unesite adresu na koju trgovina prima obavijesti.',
                        'Provjerite adresu za fizički povrat robe.',
                        'Uredite upute kupcu i tekstove potvrde.',
                        'Spremite i napravite probni zahtjev za raskid.',
                    ],
                    'warning' => 'Podaci su pravno i operativno važni. Promjene uskladite s odgovornom osobom i važećim uvjetima trgovine.',
                ],
                [
                    'id' => 'wholesale-api',
                    'title' => 'Wholesale API',
                    'eyebrow' => 'API',
                    'route' => 'admin.settings.api.wholesale',
                    'route_patterns' => ['admin.settings.api.*'],
                    'ability' => 'settings.api.manage',
                    'feature' => 'api',
                    'purpose' => 'Upravljanje korisnicima koji smiju koristiti veleprodajni API te izdavanje i opoziv njihovih tokena.',
                    'steps' => [
                        'Omogućite API pristup samo potrebnom korisniku.',
                        'Izdajte token s najmanjim potrebnim skupom ovlasti i rokom valjanosti.',
                        'Odmah sigurno kopirajte prikazani token.',
                        'Opozovite token kada više nije potreban ili postoji sumnja na kompromitaciju.',
                    ],
                    'fields' => [
                        ['name' => 'Korisnik i API pristup', 'description' => 'Određuju tko smije pristupiti veleprodajnim podacima.'],
                        ['name' => 'Ovlasti tokena', 'description' => 'Ograničavaju dopuštene API operacije.'],
                        ['name' => 'Istek', 'description' => 'Datum nakon kojeg token prestaje vrijediti.'],
                    ],
                    'warning' => 'Puna vrijednost tokena prikazuje se samo jednom. Ne šaljite je običnom e-poštom i ne spremate je u javne dokumente.',
                ],
                [
                    'id' => 'korisnicke-postavke',
                    'title' => 'Korisničke postavke',
                    'eyebrow' => 'Korisnik',
                    'route' => 'admin.settings.user.index',
                    'route_patterns' => ['admin.settings.user.*'],
                    'ability' => 'settings.user.manage',
                    'purpose' => 'Uključivanje praćenja korisnika i loyalty sustava te određivanje pravila bodovanja.',
                    'steps' => [
                        'Odlučite koristi li trgovina praćenje aktivnosti korisnika.',
                        'Ako koristite loyalty, uključite modul i postavite stopu zarade te vrijednost boda.',
                        'Postavite minimalni iznos narudžbe i dopuštene korisničke grupe.',
                        'Spremite i testirajte zaradu i korištenje bodova na probnoj narudžbi.',
                    ],
                    'fields' => [
                        ['name' => 'Praćenje korisnika', 'description' => 'Kontrolira bilježenje podržanih korisničkih događaja.'],
                        ['name' => 'Bodovi po valuti', 'description' => 'Stopa zarade loyalty bodova.'],
                        ['name' => 'Vrijednost boda', 'description' => 'Iznos popusta koji jedan bod predstavlja.'],
                        ['name' => 'Grupe', 'description' => 'Ograničavaju tko može zarađivati i koristiti bodove.'],
                    ],
                    'warning' => 'Promjena pravila ne bi trebala retroaktivno mijenjati knjižene transakcije, ali utječe na nove narudžbe. Prije objave provjerite računovodstveni učinak.',
                ],
            ],
        ],

        [
            'id' => 'korisnici',
            'title' => 'Korisnici',
            'description' => 'Korisnički računi, B2B odobrenja, grupe, ovlasti i aktivnosti.',
            'items' => [
                [
                    'id' => 'lista-korisnika',
                    'title' => 'Lista korisnika',
                    'route' => 'admin.users',
                    'route_patterns' => ['admin.users', 'admin.users.show', 'admin.users.edit'],
                    'ability' => 'users.list.view',
                    'purpose' => 'Pretraga i pregled korisničkih računa, profila, adresa, grupa, narudžbi, aktivnosti i B2B podataka.',
                    'steps' => [
                        'Pronađite korisnika po imenu, e-pošti ili drugom dostupnom filtru.',
                        'Otvorite pregled računa i provjerite uloge, grupe, adrese i nedavne narudžbe.',
                        'U uređivanju promijenite samo potvrđene podatke profila i adresa.',
                        'Ako je potrebna nova lozinka, postavite je sigurno ili uputite korisnika na Zaboravljena lozinka.',
                    ],
                    'fields' => [
                        ['name' => 'Uloga', 'description' => 'Određuje administrativna ili korisnička prava.'],
                        ['name' => 'Profil i adrese', 'description' => 'Kontaktni, poslovni, billing i shipping podaci.'],
                        ['name' => 'Grupe', 'description' => 'Utječu na cijene, akcije, loyalty i druga pravila.'],
                        ['name' => 'Narudžbe i aktivnost', 'description' => 'Povijest korisničkog i administratorskog rada povezanog s računom.'],
                    ],
                    'warning' => 'Ne dodjeljujte administratorsku ulogu bez odobrenja. Nikada ne tražite niti zapisujte korisnikovu postojeću lozinku.',
                ],
                [
                    'id' => 'b2b-zahtjevi',
                    'title' => 'B2B zahtjevi',
                    'route' => 'admin.users.b2b',
                    'route_patterns' => ['admin.users.b2b'],
                    'ability' => 'users.list.view',
                    'purpose' => 'Pregled i odobravanje poslovnih registracija te povezivanje kupca s grupom, ugovorom i ERP podacima.',
                    'steps' => [
                        'Otvorite zahtjev i provjerite tvrtku, OIB, kontakt i adrese.',
                        'Provjerite interne uvjete suradnje i potrebne ERP/ugovorne podatke.',
                        'Odaberite odgovarajuću korisničku grupu i postavite ugovorne podatke.',
                        'Odobrite ili odbijte zahtjev uz jasnu internu bilješku.',
                    ],
                    'fields' => [
                        ['name' => 'Status zahtjeva', 'description' => 'Na čekanju, odobreno ili odbijeno.'],
                        ['name' => 'Tvrtka i OIB', 'description' => 'Identitet poslovnog kupca.'],
                        ['name' => 'Grupa i ugovor', 'description' => 'Određuju B2B cijene i komercijalne uvjete.'],
                        ['name' => 'ERP podaci', 'description' => 'Identifikatori potrebni za povezivanje s poslovnim sustavom kada se koristi.'],
                    ],
                    'warning' => 'Zahtjev odobrite tek nakon poslovne provjere. Odbijanje ili promjena grupe može odmah promijeniti cijene koje korisnik vidi.',
                ],
                [
                    'id' => 'grupe-korisnika',
                    'title' => 'Grupe',
                    'route' => 'admin.users.groups',
                    'route_patterns' => ['admin.users.groups*'],
                    'ability' => 'users.groups.manage',
                    'purpose' => 'Grupiranje kupaca radi B2B cijena, akcija, loyalty pravila i drugih ciljanih funkcija.',
                    'steps' => [
                        'Izradite grupu s jasnom stabilnom šifrom i nazivom.',
                        'Postavite aktivnost, redoslijed i eventualno označite zadanu grupu.',
                        'Dodijelite korisnike grupi iz njihovog profila ili B2B obrade.',
                        'Provjerite pravila cijena i akcija vezana uz grupu.',
                    ],
                    'fields' => [
                        ['name' => 'Šifra', 'description' => 'Stabilni ključ grupe koji mogu koristiti pravila i integracije.'],
                        ['name' => 'Zadana grupa', 'description' => 'Automatski se može dodijeliti novim korisnicima.'],
                        ['name' => 'Aktivno', 'description' => 'Kontrolira može li se grupa koristiti u novim pravilima.'],
                    ],
                    'warning' => 'Brisanje ili deaktivacija grupe može utjecati na cijene velikog broja korisnika. Prvo provjerite povezana pravila.',
                ],
                [
                    'id' => 'uloge-ovlasti',
                    'title' => 'Uloge i ovlasti',
                    'route' => 'admin.users.access',
                    'route_patterns' => ['admin.users.access'],
                    'ability' => 'users.access.manage',
                    'purpose' => 'Upravljanje administratorskim ulogama i matricom dozvola za pojedine dijelove sustava.',
                    'steps' => [
                        'Odaberite ulogu koju želite pregledati.',
                        'Provjerite postojeće ovlasti po funkcionalnim grupama.',
                        'Uključite samo najmanji skup ovlasti potreban za posao te uloge.',
                        'Testirajte pristup s korisnikom te uloge prije šire primjene.',
                    ],
                    'fields' => [
                        ['name' => 'Uloga', 'description' => 'Skup ovlasti koji se dodjeljuje korisniku.'],
                        ['name' => 'Ovlast', 'description' => 'Stabilna tehnička dozvola za pregled ili promjenu pojedinog modula.'],
                        ['name' => 'Matrica', 'description' => 'Brzi pregled koje uloge imaju koju ovlast.'],
                    ],
                    'warning' => 'Ovlast admin.access omogućuje ulazak u administraciju. Ovlasti za korisnike, sustav, API i integracije dodjeljujte samo odgovornim osobama.',
                ],
                [
                    'id' => 'aktivnosti-korisnika',
                    'title' => 'Aktivnosti',
                    'route' => 'admin.users.activity',
                    'route_patterns' => ['admin.users.activity'],
                    'ability' => 'users.activity.view',
                    'purpose' => 'Pregled zabilježenih korisničkih i administratorskih događaja radi podrške i provjere promjena.',
                    'steps' => [
                        'Filtrirajte aktivnosti prema korisniku, vrsti ili vremenu.',
                        'Otvorite povezani korisnički račun kada trebate širi kontekst.',
                        'Usporedite vrijeme i opis događaja s prijavljenim problemom.',
                    ],
                    'warning' => 'Aktivnosti su pomoćni revizijski trag. Ne mijenjajte zaključke o korisniku bez provjere povezanih narudžbi i zapisa.',
                ],
                [
                    'id' => 'newsletter-prijave',
                    'title' => 'Newsletter prijave',
                    'route' => 'admin.users.newsletter',
                    'route_patterns' => ['admin.users.newsletter'],
                    'ability' => 'users.newsletter.view',
                    'purpose' => 'Pregled privola i statusa sinkronizacije newsletter pretplatnika s odabranim pružateljem usluge.',
                    'steps' => [
                        'Pronađite adresu e-pošte i provjerite izvor prijave te privolu.',
                        'Provjerite status sinkronizacije i eventualnu poruku greške.',
                        'Ponovite sinkronizaciju ili uklonite zapis samo kada je to opravdano zahtjevom korisnika ili pravilima privatnosti.',
                    ],
                    'fields' => [
                        ['name' => 'Privola', 'description' => 'Evidencija da je korisnik prihvatio newsletter komunikaciju.'],
                        ['name' => 'Provider i status', 'description' => 'Vanjski servis i rezultat sinkronizacije.'],
                        ['name' => 'Izvor i vrijeme', 'description' => 'Mjesto i trenutak nastanka prijave.'],
                    ],
                    'warning' => 'Podatke obrađujte u skladu s privolom i pravilima zaštite osobnih podataka. Brisanje može biti nepovratno.',
                ],
                [
                    'id' => 'loyalty',
                    'title' => 'Loyalty',
                    'route' => 'admin.users.loyalty',
                    'route_patterns' => ['admin.users.loyalty'],
                    'ability' => 'users.loyalty.view',
                    'feature' => 'loyalty',
                    'purpose' => 'Pregled stanja bodova i ručne korekcije kada automatsko knjiženje narudžbe treba ispravak.',
                    'steps' => [
                        'Pronađite korisnika i pregledajte trenutačno stanje te povijest knjiženja.',
                        'Provjerite povezanu narudžbu i postoje li automatsko knjiženje ili storniranje.',
                        'Za korekciju unesite pozitivan ili negativan broj bodova i jasan razlog.',
                        'Spremite i ponovno provjerite stanje korisnika.',
                    ],
                    'fields' => [
                        ['name' => 'Bodovi', 'description' => 'Pozitivan iznos dodaje, a negativan oduzima bodove.'],
                        ['name' => 'Vrsta i razlog', 'description' => 'Objašnjava zašto je knjiženje napravljeno.'],
                        ['name' => 'Narudžba', 'description' => 'Poveznica s narudžbom kada korekcija proizlazi iz kupnje.'],
                    ],
                    'warning' => 'Ručne korekcije ostaju u povijesti. Ne koristite ih za zaobilaženje pravila loyalty sustava i uvijek upišite provjerljiv razlog.',
                ],
            ],
        ],
    ],
];
