<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Ability Catalog
    |--------------------------------------------------------------------------
    |
    | Abilities are global (not model-scoped) and grouped for admin matrix UI.
    | Group supports deep tree-like keys (example: "catalog.products").
    |
    */
    'abilities' => [
        ['name' => 'admin.access', 'title' => 'Access admin panel', 'group' => 'system'],
        ['name' => 'dashboard.view', 'title' => 'View dashboard', 'group' => 'dashboard'],

        ['name' => 'catalog.categories.view', 'title' => 'View categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.create', 'title' => 'Create categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.update', 'title' => 'Update categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.delete', 'title' => 'Delete categories', 'group' => 'catalog.categories'],

        ['name' => 'catalog.products.view', 'title' => 'View products', 'group' => 'catalog.products'],
        ['name' => 'catalog.products.create', 'title' => 'Create products', 'group' => 'catalog.products'],
        ['name' => 'catalog.products.update', 'title' => 'Update products', 'group' => 'catalog.products'],
        ['name' => 'catalog.products.delete', 'title' => 'Delete products', 'group' => 'catalog.products'],
        ['name' => 'catalog.products.options.manage', 'title' => 'Manage product option values', 'group' => 'catalog.products'],

        ['name' => 'catalog.attributes.view', 'title' => 'View attributes', 'group' => 'catalog.attributes'],
        ['name' => 'catalog.attributes.create', 'title' => 'Create attributes', 'group' => 'catalog.attributes'],
        ['name' => 'catalog.attributes.update', 'title' => 'Update attributes', 'group' => 'catalog.attributes'],
        ['name' => 'catalog.attributes.delete', 'title' => 'Delete attributes', 'group' => 'catalog.attributes'],

        ['name' => 'catalog.options.view', 'title' => 'View options', 'group' => 'catalog.options'],
        ['name' => 'catalog.options.create', 'title' => 'Create options', 'group' => 'catalog.options'],
        ['name' => 'catalog.options.update', 'title' => 'Update options', 'group' => 'catalog.options'],
        ['name' => 'catalog.options.delete', 'title' => 'Delete options', 'group' => 'catalog.options'],
        ['name' => 'catalog.options.values.manage', 'title' => 'Manage option values', 'group' => 'catalog.options'],

        ['name' => 'catalog.manufacturers.view', 'title' => 'View manufacturers', 'group' => 'catalog.manufacturers'],
        ['name' => 'catalog.manufacturers.create', 'title' => 'Create manufacturers', 'group' => 'catalog.manufacturers'],
        ['name' => 'catalog.manufacturers.update', 'title' => 'Update manufacturers', 'group' => 'catalog.manufacturers'],
        ['name' => 'catalog.manufacturers.delete', 'title' => 'Delete manufacturers', 'group' => 'catalog.manufacturers'],

        ['name' => 'catalog.actions.view', 'title' => 'View actions/discounts', 'group' => 'catalog.actions'],
        ['name' => 'catalog.actions.create', 'title' => 'Create actions/discounts', 'group' => 'catalog.actions'],
        ['name' => 'catalog.actions.update', 'title' => 'Update actions/discounts', 'group' => 'catalog.actions'],
        ['name' => 'catalog.actions.delete', 'title' => 'Delete actions/discounts', 'group' => 'catalog.actions'],

        ['name' => 'sales.orders.view', 'title' => 'View orders', 'group' => 'sales.orders'],
        ['name' => 'sales.orders.update', 'title' => 'Update orders', 'group' => 'sales.orders'],
        ['name' => 'sales.orders.invoice.view', 'title' => 'View order invoices', 'group' => 'sales.orders'],

        ['name' => 'content.blog.view', 'title' => 'View blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.create', 'title' => 'Create blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.update', 'title' => 'Update blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.delete', 'title' => 'Delete blog posts', 'group' => 'content.blog'],

        ['name' => 'content.pages.view', 'title' => 'View info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.create', 'title' => 'Create info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.update', 'title' => 'Update info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.delete', 'title' => 'Delete info pages', 'group' => 'content.pages'],

        ['name' => 'content.faqs.view', 'title' => 'View FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.create', 'title' => 'Create FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.update', 'title' => 'Update FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.delete', 'title' => 'Delete FAQs', 'group' => 'content.faqs'],

        ['name' => 'content.comments.view', 'title' => 'View comments', 'group' => 'content.comments'],
        ['name' => 'content.comments.moderate', 'title' => 'Moderate comments', 'group' => 'content.comments'],
        ['name' => 'content.comments.delete', 'title' => 'Delete comments', 'group' => 'content.comments'],

        ['name' => 'content.blocks.view', 'title' => 'View content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.create', 'title' => 'Create content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.update', 'title' => 'Update content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.delete', 'title' => 'Delete content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.navigation.view', 'title' => 'View main navigation setup', 'group' => 'content.navigation'],
        ['name' => 'content.navigation.update', 'title' => 'Update main navigation setup', 'group' => 'content.navigation'],

        ['name' => 'content.slots.view', 'title' => 'View content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.create', 'title' => 'Create content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.update', 'title' => 'Update content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.delete', 'title' => 'Delete content slots', 'group' => 'content.slots'],

        ['name' => 'media.manage', 'title' => 'Manage media', 'group' => 'content.media'],

        ['name' => 'users.list.view', 'title' => 'View users', 'group' => 'users.core'],
        ['name' => 'users.profile.update', 'title' => 'Update user profiles', 'group' => 'users.core'],
        ['name' => 'users.groups.manage', 'title' => 'Manage user groups', 'group' => 'users.groups'],
        ['name' => 'users.activity.view', 'title' => 'View user activity', 'group' => 'users.activity'],
        ['name' => 'users.loyalty.view', 'title' => 'View loyalty ledger', 'group' => 'users.loyalty'],
        ['name' => 'users.loyalty.adjust', 'title' => 'Adjust loyalty points', 'group' => 'users.loyalty'],
        ['name' => 'users.access.manage', 'title' => 'Manage roles & abilities', 'group' => 'users.access'],

        ['name' => 'settings.local.manage', 'title' => 'Manage local settings', 'group' => 'settings.local'],
        ['name' => 'settings.system.runtime.manage', 'title' => 'Manage runtime controls', 'group' => 'settings.system'],
        ['name' => 'settings.system.admin_appearance.manage', 'title' => 'Manage admin appearance settings', 'group' => 'settings.system'],
        ['name' => 'settings.system.catalog_features.manage', 'title' => 'Manage catalog feature flags', 'group' => 'settings.system'],
        ['name' => 'settings.api.manage', 'title' => 'Manage API settings', 'group' => 'settings.api'],
        ['name' => 'settings.user.manage', 'title' => 'Manage user settings', 'group' => 'settings.user'],

        ['name' => 'ai.admin.use', 'title' => 'Use admin AI assistant', 'group' => 'system.ai'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Role Ability Map
    |--------------------------------------------------------------------------
    */
    'roles' => [
        'admin' => [
            'admin.access',
            'dashboard.view',
            'catalog.categories.view',
            'catalog.categories.create',
            'catalog.categories.update',
            'catalog.categories.delete',
            'catalog.products.view',
            'catalog.products.create',
            'catalog.products.update',
            'catalog.products.delete',
            'catalog.products.options.manage',
            'catalog.attributes.view',
            'catalog.attributes.create',
            'catalog.attributes.update',
            'catalog.attributes.delete',
            'catalog.options.view',
            'catalog.options.create',
            'catalog.options.update',
            'catalog.options.delete',
            'catalog.options.values.manage',
            'catalog.manufacturers.view',
            'catalog.manufacturers.create',
            'catalog.manufacturers.update',
            'catalog.manufacturers.delete',
            'catalog.actions.view',
            'catalog.actions.create',
            'catalog.actions.update',
            'catalog.actions.delete',
            'sales.orders.view',
            'sales.orders.update',
            'sales.orders.invoice.view',
            'content.blog.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.delete',
            'content.pages.view',
            'content.pages.create',
            'content.pages.update',
            'content.pages.delete',
            'content.faqs.view',
            'content.faqs.create',
            'content.faqs.update',
            'content.faqs.delete',
            'content.comments.view',
            'content.comments.moderate',
            'content.comments.delete',
            'content.blocks.view',
            'content.blocks.create',
            'content.blocks.update',
            'content.blocks.delete',
            'content.navigation.view',
            'content.navigation.update',
            'content.slots.view',
            'content.slots.create',
            'content.slots.update',
            'content.slots.delete',
            'media.manage',
            'users.list.view',
            'users.profile.update',
            'users.groups.manage',
            'users.activity.view',
            'users.loyalty.view',
            'users.loyalty.adjust',
            'settings.local.manage',
            'settings.system.runtime.manage',
            'settings.system.admin_appearance.manage',
            'settings.api.manage',
            'settings.user.manage',
            'ai.admin.use',
        ],
        'editor' => [
            'admin.access',
            'dashboard.view',
            'catalog.categories.view',
            'catalog.products.view',
            'catalog.products.update',
            'catalog.products.options.manage',
            'catalog.attributes.view',
            'catalog.options.view',
            'catalog.options.values.manage',
            'catalog.manufacturers.view',
            'sales.orders.view',
            'sales.orders.invoice.view',
            'content.blog.view',
            'content.blog.create',
            'content.blog.update',
            'content.pages.view',
            'content.pages.create',
            'content.pages.update',
            'content.faqs.view',
            'content.faqs.create',
            'content.faqs.update',
            'content.comments.view',
            'content.comments.moderate',
            'content.blocks.view',
            'content.blocks.create',
            'content.blocks.update',
            'content.navigation.view',
            'content.navigation.update',
            'content.slots.view',
            'content.slots.create',
            'content.slots.update',
            'media.manage',
        ],
        'customer' => [],
    ],
];
